"""add app_api_docs

Revision ID: 32689a98a560
Revises: 532b3f888abf
Create Date: 2025-08-13 09:45:38.589357

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32689a98a560'
down_revision = '532b3f888abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_api_docs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('app_mode', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', models.types.StringUUID(), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('endpoints', sa.String(length=255), nullable=False),
    sa.Column('curl_examples', sa.TEXT(), nullable=True),
    sa.Column('python_examples', sa.TEXT(), nullable=True),
    sa.Column('inputs_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mock_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mq_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', models.types.StringUUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_api_docs_pkey')
    )
    with op.batch_alter_table('app_api_docs', schema=None) as batch_op:
        batch_op.create_index('idx_app_api_docs_api_key', ['api_key'], unique=False)
        batch_op.create_index('idx_app_api_docs_app_mode', ['app_mode'], unique=False)
        batch_op.create_index('idx_app_api_docs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_app_api_docs_tenant_app', ['tenant_id', 'app_id'], unique=False)
        batch_op.create_index('idx_app_api_docs_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_app_api_docs_workflow', ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_api_docs', schema=None) as batch_op:
        batch_op.drop_index('idx_app_api_docs_workflow')
        batch_op.drop_index('idx_app_api_docs_updated_at')
        batch_op.drop_index('idx_app_api_docs_tenant_app')
        batch_op.drop_index('idx_app_api_docs_created_at')
        batch_op.drop_index('idx_app_api_docs_app_mode')
        batch_op.drop_index('idx_app_api_docs_api_key')

    op.drop_table('app_api_docs')
    # ### end Alembic commands ###
